version: '3.7'
services:
  applybot:
    container_name: applybot
    image: luwol03/applybot
    # image: luwol03/applybot:experimental
    restart: always
    tty: true
    depends_on:
      - db
    environment:
      TOKEN: '<TOKEN>'
      DB_HOST: 'db'
      DB_PORT: 3306
      DB_DATABASE: 'applybot'
      DB_USER: 'applybot'
      DB_PASSWORD: 'applybot'
      SENTRY_DSN: ''
      OWNER_ID: ''

  db:
    container_name: mariadb
    image: mariadb
    # image: jsurf/rpi-mariadb
    restart: always
    environment:
      MYSQL_USER: 'applybot'
      MYSQL_PASSWORD: 'applybot'
      MYSQL_DATABASE: 'applybot'
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      # MYSQL_INITDB_SKIP_TZINFO: 'yes'
    volumes:
      - './mysql_data:/var/lib/mysql'
